# Generated by Django 4.0 on 2022-01-02 06:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('dod', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('profile_picture', models.ImageField(upload_to='media/authors')),
            ],
        ),
    ]
