# Generated by Django 4.0 on 2022-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_category_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(upload_to='covers'),
        ),
    ]
