# Generated by Django 4.0 on 2022-01-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_author_profile_picture_alter_book_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
