# Generated by Django 4.0 on 2022-01-03 06:39

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to=webapp.models.get_file_path),
        ),
    ]
