# Generated by Django 4.0 on 2022-01-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('webapp', '0007_bookread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookread',
            name='ip',
        ),
        migrations.AddField(
            model_name='bookread',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
