# Generated by Django 4.0 on 2022-01-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_book_language_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookread',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookread',
            name='page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
