# Generated by Django 4.0 on 2022-01-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_bookread_completed_bookread_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookread',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
