# Generated by Django 4.0 on 2022-01-09 13:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_follow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#5CD17B', image_field=None, max_length=18, samples=None),
        ),
    ]
