# Generated by Django 4.0 on 2022-01-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_changepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePassword',
        ),
    ]
