# Generated by Django 4.0 on 2022-01-11 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_changepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepassword',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
