# Generated by Django 4.0 on 2022-01-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_book_language_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
