# Generated by Django 4.0 on 2022-01-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_subscription_amount_alter_subscription_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
