from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('policy/', views.policy, name='policy'),
    path('terms/', views.terms, name='terms'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/upload', views.profile_upload, name='profile_upload'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('details/', views.details, name='details'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('change-password/<uuid:key>', views.change_password, name='change_password'),
    path('forgot-username/', views.forgot_username, name='forgot_username'),
    path('library/', views.library, name='library'),
    path('categories/', views.categories, name='categories'),
    path('category/<int:id>', views.category, name='category'),
    path('popular/', views.popular, name='popular'),
    path('recommended/', views.recommended, name='recommended'),
    path('latest/', views.latest, name='latest'),
    path('most-read/', views.most_read, name='most_read'),
    path('authors/', views.authors, name='authors'),
    path('authors/follow', views.follow_author, name='follow_author'),
    path('authors/search', views.author_search, name='author_search'),
    path('library/search', views.library_search, name='library_search'),
    path('categories/search', views.category_search, name='category_search'),
    path('search/', views.search, name='search'),
    path('book/<int:id>', views.book, name='book'),
    path('author/<int:id>', views.author, name='author'),
    path('book/add-to-library', views.add_to_library, name='add_to_library'),
    path('library/delete-from-library', views.remove_from_library, name='remove_from_library'),
    path('read/<int:id>', views.read, name='read'),
    path('read/next-page', views.get_next_page, name='get_next_page'),
    path('read/prev-page', views.get_prev_page, name='get_prev_page'),
    path('read/first-page', views.get_first_page, name='get_first_page'),
    path('read/last-page', views.get_last_page, name='get_last_page'),
    path('read/go-to-page', views.go_to_page, name='go_to_page'),
]